#  _____     _      __  __            _                 
# |_   _|__ | | ___|  \/  | __ _ _ __(_) __ _ _ __ ___  
#   | |/ _ \| |/ _ \ |\/| |/ _` | '__| |/ _` | '_ ` _ \ 
#   | | (_) | |  __/ |  | | (_| | |  | | (_| | | | | | |
#   |_|\___/|_|\___|_|  |_|\__,_|_|  |_|\__,_|_| |_| |_|

indent_type = "Spaces"
indent_width = 2
column_width = 120
